### PR TITLE
update to 1.3.0

### PR DESCRIPTION
**Pull request by dvtkrlbs**

### CODE REVIEW

**Comment by michaeleisel** [comment]
thanks

**Comment by dvtkrlbs** [comment]
hmm i actually get a compile error 
```sh
Last 15 lines from /Users/dvtkrlbs/Library/Logs/Homebrew/zld/02.make:
[100%] Built target flags_parse
find abseil-cpp-20200225/build_arm64/absl -name '*.a' | xargs libtool -static -o abseil-cpp-20200225/build/libabsl_arm64.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning same member name (escaping.cc.o) in output file used for input files: abseil-cpp-20200225/build_arm64/absl/strings/libabsl_strings.a(escaping.cc.o) and: abseil-cpp-20200225/build_arm64/absl/strings/libabsl_strings_internal.a(escaping.cc.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning same member name (flag.cc.o) in output file used for input files: abseil-cpp-20200225/build_arm64/absl/flags/libabsl_flags_internal.a(flag.cc.o) and: abseil-cpp-20200225/build_arm64/absl/flags/libabsl_flags.a(flag.cc.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning same member name (usage.cc.o) in output file used for input files: abseil-cpp-20200225/build_arm64/absl/flags/libabsl_flags_usage.a(usage.cc.o) and: abseil-cpp-20200225/build_arm64/absl/flags/libabsl_flags_usage_internal.a(usage.cc.o) due to use of basename, truncation and blank padding
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: abseil-cpp-20200225/build_arm64/absl/strings/libabsl_strings.a(string_view.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: abseil-cpp-20200225/build_arm64/absl/types/libabsl_bad_optional_access.a(bad_optional_access.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: abseil-cpp-20200225/build_arm64/absl/types/libabsl_bad_any_cast_impl.a(bad_any_cast.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: abseil-cpp-20200225/build_arm64/absl/types/libabsl_bad_variant_access.a(bad_variant_access.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: abseil-cpp-20200225/build_arm64/absl/flags/libabsl_flags.a(flag.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: abseil-cpp-20200225/build_arm64/absl/debugging/libabsl_debugging_internal.a(elf_mem_image.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: abseil-cpp-20200225/build_arm64/absl/debugging/libabsl_debugging_internal.a(vdso_support.cc.o) has no symbols
lipo -create abseil-cpp-20200225/build/libabsl_x86_64.a abseil-cpp-20200225/build/libabsl_arm64.a -output abseil-cpp-20200225/build/libabsl.a
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: abseil-cpp-20200225/build/libabsl_x86_64.a and abseil-cpp-20200225/build/libabsl_arm64.a have the same architectures (x86_64) and can't be in the same fat output file
make: *** [abseil-cpp-20200225] Error 1
```

i am not sure if this is from the updated brew file but sorry i should have tested it better

**Comment by dvtkrlbs** [comment]
i created a reverting pr just to be sure. also openning a relevant issue on the main repo

**Comment by dvtkrlbs** [comment]
ok i tried manual build and it works. will try to clean my brew cache and give feedback

**Pull request merged**
